version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'ci-rmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - /logs:/var/lib/rabbitmq/
        - /logs/:/var/log/rabbitmq
    networks:
        - ci_rmq_net

networks:
  ci_rmq_net:
    driver: bridge
